# Generated by Django 4.2.7 on 2024-04-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Admin_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_contact', models.CharField(max_length=10)),
                ('admin_email', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_details', models.CharField(max_length=100)),
                ('info_date', models.DateTimeField()),
                ('info_title', models.CharField(max_length=50)),
                ('info_file', models.FileField(upload_to='InfoDocs/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=20)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_marketupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('market_rate', models.CharField(max_length=50)),
                ('update_date', models.DateField(null=True)),
                ('productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product_category')),
            ],
        ),
    ]
