# Generated by Django 4.2.7 on 2024-04-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=100)),
                ('product_rate', models.CharField(max_length=50)),
                ('product_image', models.FileField(upload_to='Productimage/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_farmer_registration')),
                ('productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product_category')),
            ],
        ),
    ]
