# Generated by Django 4.2.7 on 2024-04-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('user_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('user_password', models.CharField(max_length=50)),
                ('user_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_farmer_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=20)),
                ('farmer_email', models.CharField(max_length=20)),
                ('farmer_contact', models.CharField(max_length=20)),
                ('farmer_address', models.CharField(max_length=20)),
                ('farmer_photo', models.FileField(upload_to='farmers/photo/')),
                ('farmer_proof', models.FileField(upload_to='farmers/proof/')),
                ('farmer_password', models.CharField(max_length=20)),
                ('farmer_status', models.IntegerField(default='0')),
                ('farmer_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
